### ISSUE TITLE
Font in code block

### ISSUE THREAD

**Issue by wey-gu** [IncredibleDevHQ/Incredible#5]
### What problem are you facing?

The font rendered in the code block now isn't mono, thus the width is not equal for all characters.

### What's the solution you would like to see?

Use a mono font like `JetBrains Mono`

### What alternatives did you consider?

n/a

### Anything to add? (optional)

thanks!!!

**Comment by hackintoshrao** [comment]
@wey-gu This is fixed, we'll send a PR soon.

**Comment by wey-gu** [comment]
> @wey-gu This is fixed, we'll send a PR soon. 

Wow, thanks!!
